#!name=过期啦
#!desc=过期啦解锁会员
#!homepage=https://github.com/abisuq
#!author=89996462
#!icon=https://raw.githubusercontent.com/abisuq/private/main/icons/gql.png

[Script]
过期啦=type=http-response,pattern=^https:\/\/expire\.vanemu\.com\/1\.1\/functions\/getUserInfo,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/gql.js
[MITM] 
hostname = %APPEND% expire.vanemu.com